import type { RawAIRecommendation } from '@/types';

export const MOCK_RECOMMENDATIONS: RawAIRecommendation[] = [
  {
    title: 'Never Let Me Go',
    author: 'Kazuo Ishiguro',
    matchScore: 95,
    oneSentenceHook: 'A quietly devastating novel about memory, identity, and what it means to be human.',
    premise: 'Set in a secluded English boarding school called Hailsham, the novel follows Kathy and her childhood friends Tommy and Ruth as they grow up sheltered from the outside world — slowly uncovering the disturbing truth about their place in society and what their futures hold.',
    whyItFits:
      "Ishiguro's restrained, melancholic prose creates an atmosphere of creeping dread that mirrors the emotional weight you loved. The characters carry an inner complexity rarely matched in literary fiction, and the themes of loss and acceptance resonate across every chapter.",
    matchingDimensions: ['tone', 'characters', 'writingStyle', 'emotionalFeel'],
    possibleMismatch: 'The pacing is very deliberate — readers expecting plot-driven tension may find it too quiet.',
    tags: ['dystopian', 'literary', 'melancholic', 'introspective', 'British'],
    difficulty: 'medium',
    pacing: 'slow',
  },
  {
    title: 'The Secret History',
    author: 'Donna Tartt',
    matchScore: 91,
    oneSentenceHook: 'A lush, morally complex thriller where beauty and darkness are inseparable.',
    premise: 'A group of elite classics students at a small Vermont college, led by a charismatic professor, become consumed by the pursuit of a transcendent Dionysian experience. When their experiment goes too far, one of their own is killed — and what follows is a long, suffocating reckoning with guilt.',
    whyItFits:
      "Tartt's writing is richly atmospheric and character-driven, with a tight-knit group whose relationships carry the full weight of the narrative. The themes of obsession, guilt, and the aestheticisation of evil give it real thematic depth beyond its thriller surface.",
    matchingDimensions: ['writingStyle', 'characters', 'themes', 'tone'],
    possibleMismatch: 'The premise is revealed in the opening pages, so tension comes from character psychology rather than plot mystery.',
    tags: ['literary thriller', 'dark academia', 'obsession', 'guilt', 'atmospheric'],
    difficulty: 'medium',
    pacing: 'moderate',
  },
  {
    title: 'A Gentleman in Moscow',
    author: 'Amor Towles',
    matchScore: 87,
    oneSentenceHook: 'An elegant, witty novel proving that a confined life can still be richly lived.',
    premise: 'In 1922, Count Alexander Rostov is sentenced to lifelong house arrest in Moscow\'s Metropol Hotel — a grand, gilded world he may never leave. Over the following decades, confined to his suite and the hotel\'s corridors, he builds a quiet, remarkable life within those walls.',
    whyItFits:
      "Towles writes with precision and warmth, and his protagonist is one of the most fully realised characters in recent literary fiction. The novel's unhurried pace and introspective quality reward readers who value atmosphere and character over plot.",
    matchingDimensions: ['characters', 'writingStyle', 'emotionalFeel', 'setting'],
    possibleMismatch: 'The plot is deliberately low-stakes; readers seeking dramatic tension may feel underwhelmed.',
    tags: ['historical', 'charming', 'literary', 'Russia', 'elegant'],
    difficulty: 'easy',
    pacing: 'slow',
  },
  {
    title: 'The Remains of the Day',
    author: 'Kazuo Ishiguro',
    matchScore: 89,
    oneSentenceHook: 'A master of repression narrates a life of quiet self-deception in prose of exquisite control.',
    premise: 'Stevens, the consummate English butler, embarks on a rare motoring trip through the countryside to visit a former colleague. As he travels, he reflects on his decades of devoted service to Darlington Hall — and slowly, painfully, on the choices and sacrifices that defined his life.',
    whyItFits:
      "Ishiguro's writing here is a masterclass in what is not said — the emotional restraint creates a resonance that builds steadily. The complexity of the narrator's self-awareness (or lack of it) and the themes of dignity, regret, and duty make this a deeply rewarding read.",
    matchingDimensions: ['writingStyle', 'characters', 'tone', 'complexity', 'themes'],
    possibleMismatch: "The unreliable narrator's limited self-insight can frustrate readers who prefer emotionally open protagonists.",
    tags: ['literary', 'British', 'regret', 'repression', 'Booker Prize'],
    difficulty: 'medium',
    pacing: 'slow',
  },
  {
    title: 'Outline',
    author: 'Rachel Cusk',
    matchScore: 83,
    oneSentenceHook: 'A radical novel where the narrator disappears and other lives fill the void.',
    premise: 'Following a divorce and a move to Athens, a writer named Faye takes a teaching position and meets a series of strangers on the plane, at dinner, in class. She says very little about herself — instead, the people she encounters tell her their stories, and through those stories, a portrait of her emerges.',
    whyItFits:
      "Cusk's autofiction trilogy redefines what a novel can do with interiority and point of view. The writing style is unlike almost anything else — cool, precise, and revelatory — and the themes of identity, loss, and reinvention are explored with rigour.",
    matchingDimensions: ['writingStyle', 'complexity', 'themes', 'emotionalFeel'],
    possibleMismatch: 'The experimental, plotless structure will not work for readers who need narrative momentum.',
    tags: ['autofiction', 'experimental', 'literary', 'identity', 'contemporary'],
    difficulty: 'hard',
    pacing: 'slow',
  },
  {
    title: 'Stoner',
    author: 'John Williams',
    matchScore: 88,
    oneSentenceHook: 'A quiet, devastating account of an ordinary life lived with extraordinary dignity.',
    premise: 'William Stoner is a Missouri farm boy who stumbles into a love of literature at university and becomes an English professor. The novel traces his entire adult life — his marriage, career, passions, and failures — with an unflinching simplicity that transforms the ordinary into something profound.',
    whyItFits:
      "Williams's prose is clean and unsparing, carrying enormous emotional weight through restraint rather than drama. The novel's meditation on work, love, failure, and the value of a life makes it one of the most emotionally resonant rediscoveries of recent years.",
    matchingDimensions: ['writingStyle', 'emotionalFeel', 'characters', 'themes'],
    possibleMismatch: "The subject matter — an academic's largely uneventful life — may feel too quiet for some readers.",
    tags: ['literary', 'quiet', 'academic', 'American', 'rediscovered classic'],
    difficulty: 'easy',
    pacing: 'slow',
  },
  {
    title: 'Pachinko',
    author: 'Min Jin Lee',
    matchScore: 84,
    oneSentenceHook: 'A multigenerational saga where fate, identity, and prejudice shape four generations of a Korean family.',
    premise: 'Beginning in early 20th-century Korea, the novel follows a young woman whose illegitimate pregnancy sets in motion a century-long family story. Her descendants migrate to Japan, where they face discrimination, reinvention, and the question of what it means to belong — to a place, a culture, and a name.',
    whyItFits:
      'Lee builds characters with astonishing depth, each one carrying the full weight of their historical moment. The themes of identity, belonging, sacrifice, and discrimination are explored at both intimate and epic scale.',
    matchingDimensions: ['characters', 'themes', 'emotionalFeel', 'complexity'],
    possibleMismatch: 'The scope is very wide — readers seeking a tightly focused, introspective narrative may find it sprawling.',
    tags: ['multigenerational', 'Korean', 'historical', 'family', 'identity'],
    difficulty: 'medium',
    pacing: 'moderate',
  },
  {
    title: 'The Dispossessed',
    author: 'Ursula K. Le Guin',
    matchScore: 79,
    oneSentenceHook: 'A rigorous, humane science fiction novel that uses two worlds to ask what freedom truly means.',
    premise: 'Shevek is a brilliant physicist from Anarres, a sparse anarchist moon, who travels to the lush twin planet Urras — a world of abundance, inequality, and political intrigue. His journey becomes both a scientific mission and a reckoning with what freedom, ownership, and society actually mean.',
    whyItFits:
      "Le Guin's prose is measured and thoughtful, and her world-building serves theme rather than spectacle. The novel's philosophical depth and its quietly radical ideas about society, science, and human nature reward careful readers.",
    matchingDimensions: ['themes', 'complexity', 'writingStyle', 'setting'],
    possibleMismatch: 'The pacing is deliberately slow and the political philosophy is foregrounded — readers seeking action will be disappointed.',
    tags: ['science fiction', 'philosophical', 'anarchism', 'Le Guin', 'classic'],
    difficulty: 'medium',
    pacing: 'slow',
  },
];
